"""
Django settings for vweb project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

REACT_APP_DIR = os.path.join(os.path.dirname(BASE_DIR), 'vclient')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xr=%v01z@^t*ro^_1*)4ya(%42_9^*wdvw_^4jr85=@gnu1g)4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


CORS_ORIGIN_ALLOW_ALL = True


# Application definition

INSTALLED_APPS = [
    'channels',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vweb.vclient.apps.VclientConfig',
    'rest_framework'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vweb.vweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vweb.vweb.wsgi.application'

ASGI_APPLICATION = 'vweb.vweb.asgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'vweb',
        'USER': 'vweb',
        'PASSWORD': 'vbetserver',
        'HOST': 'localhost',
        'PORT': '',
    }
}

AUTH_USER_MODEL = 'vclient.User'

AUTHENTICATION_BACKENDS = [
    'vweb.vclient.backends.UserAuthentication',
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}

REDIS_URI = 'redis://localhost:6379'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, '../data/static')

PROVIDERS = [
    'betika',
    'mozzart',
    'merrybet',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'admin@vbettrader.com'
EMAIL_HOST_PASSWORD = 'updatemenow'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'Admin <admin@vbettrader.com>'

LOG_LEVEL = 'DEBUG'
LOG_DIR = '/var/log'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)-8s:%(name)-12s] %(message)s',
        },
        'error-logger': {
            'format': '%(asctime)s %(filename)s [%(lineno)d ] [%(pathname)s] %(message)s'
        }
    },
    'handlers': {
        'default': {
            'level': LOG_LEVEL,
            'formatter': 'standard',
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
        },
        'file': {
            'level': LOG_LEVEL,
            'class': "logging.handlers.RotatingFileHandler",
            'formatter': 'standard',
            "filename": f'{LOG_DIR}/vweb.log',
            "maxBytes": 100000000,
            "backupCount": 10,
        },
    },
    'loggers': {
        '': {
            'handlers': ['file', 'default'],
            'level': 'DEBUG',
            'propagate': False
        },
        'aioredis': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False
        },
        'error-logger': {
            'handlers': ['file', 'default'],
            'level': 'DEBUG',
            'propagate': False
        }
    }
}